import numpy as np
from typing import Optional, List

class CoreTensor:
    """Tenseur géré par le backend Rust et intégré à la différentiation automatique."""
    
    def __init__(self, data: np.ndarray) -> None: ...
    
    def add(self, other: "CoreTensor") -> "CoreTensor": ...
    def sub(self, other: "CoreTensor") -> "CoreTensor": ...
    def mul(self, other: "CoreTensor") -> "CoreTensor": ...
    def div(self, other: "CoreTensor") -> "CoreTensor": ...
    def pow(self,other: "CoreTensor") -> "CoreTensor": ...
    def matmul(self,other: "CoreTensor") -> "CoreTensor": ...
    def neg(self) -> "CoreTensor": ...
    def add_assign(self, other: "CoreTensor") -> None: ...    
    def sub_assign(self, other: "CoreTensor") -> None: ...    
    def mul_assign(self, other: "CoreTensor") -> None: ...    
    def div_assign(self, other: "CoreTensor") -> None: ...    
    def matmul_assign(self, other: "CoreTensor"): ...    

    def add_scalar(self, other: np.float32) -> "CoreTensor": ...
    def sub_scalar(self, other: np.float32) -> "CoreTensor": ...
    def mul_scalar(self, other: np.float32) -> "CoreTensor": ...
    def div_scalar(self, other: np.float32) -> "CoreTensor": ...
    def add_scalar_assign(self, other: "CoreTensor") -> None: ...   
    def sub_scalar_assign(self, other: "CoreTensor") -> None: ...   
    def mul_scalar_assign(self, other: "CoreTensor") -> None: ...   
    def div_scalar_assign(self, other: "CoreTensor") -> None: ...   

    def __add__(self, other: "CoreTensor") -> "CoreTensor": ...
    def __sub__(self, other: "CoreTensor") -> "CoreTensor": ...
    def __mul__(self, other: "CoreTensor") -> "CoreTensor": ...
    def __truediv__(self, other: "CoreTensor") -> "CoreTensor": ...
    def __truediv__(self, other: "CoreTensor") -> "CoreTensor": ...
    def __pow__(self, other: "CoreTensor") -> "CoreTensor": ...
    def __matmul__(self, other: "CoreTensor") -> "CoreTensor": ...
    def __neg__(self) -> "CoreTensor": ...
    
    def __iadd__(self, other: "CoreTensor") -> None: ...
    def __isub__(self, other: "CoreTensor") -> None: ...
    def __imul__(self, other: "CoreTensor") -> None: ...
    def __itruediv__(self, other: "CoreTensor") -> None: ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

    def to_numpy(self) -> np.ndarray: ...
    def backward(self, all_parameters: List["Parameter"]) -> None: ...

class Parameter:
    """Paramètre représentant les poids et les biais des modèles. Variables mutables in-place."""
    
    @property
    def tensor(self) -> Optional[CoreTensor]: ...
    
    @property
    def grad(self) -> Optional[CoreTensor]: ...
    
    def add_assign(self, other: "CoreTensor") -> None: ...    
    def sub_assign(self, other: "CoreTensor") -> None: ...    
    def mul_assign(self, other: "CoreTensor") -> None: ...    
    def div_assign(self, other: "CoreTensor") -> None: ...   

    def __iadd__(self, other: "CoreTensor") -> None: ...
    def __isub__(self, other: "CoreTensor") -> None: ...
    def __imul__(self, other: "CoreTensor") -> None: ...
    def __itruediv__(self, other: "CoreTensor") -> None: ...
    